// <auto-generated />
using System;
using System.Collections.Generic;
using CinemaBooking.Modules.Cinemas.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CinemaBooking.Modules.Cinemas.Core.Data.Migrations
{
    [DbContext(typeof(CinemasDbContext))]
    partial class CinemasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("cinemas")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CinemaBooking.Modules.Cinemas.Core.Entities.Cinema", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "CinemaBooking.Modules.Cinemas.Core.Entities.Cinema.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired();

                            b1.Property<string>("ZipCode")
                                .IsRequired();

                            b1.ToJson("Address");
                        });

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Screens", "CinemaBooking.Modules.Cinemas.Core.Entities.Cinema.Screens#Screen", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.ComplexCollection(typeof(List<Dictionary<string, object>>), "Seats", "CinemaBooking.Modules.Cinemas.Core.Entities.Cinema.Screens#Screen.Seats#Seat", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<Guid>("Id");

                                    b2.Property<int>("Number");

                                    b2.Property<string>("Row")
                                        .IsRequired();

                                    b2.Property<int>("Type");

                                    b2.ToJson("Seats");
                                });

                            b1.ToJson("Screens");
                        });

                    b.HasKey("Id");

                    b.ToTable("Cinemas", "cinemas");
                });
#pragma warning restore 612, 618
        }
    }
}
